version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
# "docker compose up -d" para subir o container, -d para rodar em detached(segundo plano, sem mostrar os logs)
# "docker compose ps" para ver os containers rodando
# "docker compose stop" para parar os containers
# "docker compose down" para deletar todos os containers
